quarkus:
  http:
    port: 8080
    cors:
      ~: true
      methods: GET,PUT,POST,PATCH,DELETE
  log:
    console:
      enable: true
  datasource:
    url: jdbc:postgres://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    driver: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  oidc:
    auth-server-url: https://keycloak.bts-crew.com/auth/realms/${KEYCLOAK_REALM}
    client-id: ${KEYCLOAK_CLIENT_ID}
    credentials:
      secret: ${KEYCLOAK_CLIENT_SECRET}
  keycloak:
    policy-enforcer:
      enable: false

# Dev profile
"%dev":
  quarkus:
    http:
      port: ${APP_PORT:8021}
    datasource:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:6021}/${DB_DATABASE:backstage}
      driver: org.postgresql.Driver
      username: ${DB_USERNAME:developer}
      password: ${DB_PASSWORD:developer}
    hibernate-orm:
      database:
        generation: drop-and-create
    swagger-ui:
      path: /docs
    oidc:
      enabled: ${AUTH_ENABLED:true}
      auth-server-url: https://keycloak.bts-crew.com/auth/realms/nonprod
      client-id: ${KEYCLOAK_CLIENT_ID:site-api}
      credentials:
        secret: ${KEYCLOAK_CLIENT_SECRET}

# Test profile
"%test":
  quarkus:
    datasource:
      url: jdbc:h2:mem:newton-engineer
      driver: org.h2.Driver
      username: sa
      password:
    oidc:
      enabled: false
      auth-server-url: http://localhost:8080
      client-id: none
      credentials:
        secret: none
