sonar:
  extends: .gradle
  stage: quality
  needs:
    - test
    - test-docker-image
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
  script: ./gradlew sonarqube
